name: Vercel Deploy
description: Deploys a reference app to Vercel
inputs:
  vercel-org-id:
    description: Vercel Organisation ID
    required: true
  vercel-project-id:
    description: Vercel Project ID
    required: true
  vercel-token:
    description: Vercel Access Token
    required: true
  vercel-environment:
    description: Vercel environment (production / preview)
    required: false
    default: "preview"
  dir:
    description: App directory
    required: true
  saas-account-id:
    description: The Account ID for the SaaS deployment
    required: false
outputs:
  url:
    description: The deployed app URL
    value: ${{ steps.deployment-url.outputs.url }}
runs:
  using: composite
  steps:
    - run: |
        echo "VERCEL_ORG_ID=${{ inputs.vercel-org-id }}" >> $GITHUB_ENV
        echo "VERCEL_PROJECT_ID=${{ inputs.vercel-project-id }}" >> $GITHUB_ENV
        echo "VERCEL_ENVIRONMENT=${{ inputs.vercel-environment }}" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_SAAS_ACCOUNT_ID=${{ inputs.saas-account-id }}" >> $GITHUB_ENV
      shell: bash
    - name: Install Vercel CLI
      shell: bash
      run: npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      shell: bash
      run: vercel pull --yes --environment=${{ inputs.vercel-environment }} --token=${{ inputs.vercel-token }}
    - name: Pull Vercel Environment Variables to .env file
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: vercel env pull --yes --environment=${{ inputs.vercel-environment }} --token=${{ inputs.vercel-token }} .env.local
    - name: Development Build
      shell: bash
      if: inputs.vercel-environment != 'production'
      run: vercel build --token=${{ inputs.vercel-token }}
    - name: Production build
      shell: bash
      if: inputs.vercel-environment == 'production'
      run: vercel build --prod --token=${{ inputs.vercel-token }}
    - name: Deploy to Vercel (Preview)
      shell: bash
      if: inputs.vercel-environment != 'production'
      run: vercel deploy --prebuilt --token=${{ inputs.vercel-token }} > deployment-url.txt
    - name: Deploy to Vercel (Production)
      shell: bash
      if: inputs.vercel-environment == 'production'
      run: vercel deploy --prebuilt --token=${{ inputs.vercel-token }} > deployment-url.txt
    - name: Output Deployment URL
      id: deployment-url
      shell: bash
      run: |
        URL=$(cat deployment-url.txt)
        echo "url=$URL" >> $GITHUB_OUTPUT
